- repo: local
  hooks:
    - id: yapf
      name: yapf
      language: system
      entry: yapf
      types: [python]
      args: ['-i', '-r']
    - id: flake8
      name: flake8
      language: system
      entry: flake8
      types: [python]
